name: t21-thurs-harmonica
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - numpy
  - pandas
  - xarray
  - matplotlib
  - jupyterlab
  - pyproj
  # Fatiando a Terra libraries
  - pooch
  - harmonica
  - verde
  - boule
